-- Correspond à docs/diagrammes/D2-modele-donnees.md — toute divergence doit être corrigée dans les deux.

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL
);

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(120) NOT NULL,
    promotion_id  BIGINT NOT NULL REFERENCES promotion(id)
);

CREATE TABLE session (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre          VARCHAR(200) NOT NULL,
    promotion_id   BIGINT NOT NULL REFERENCES promotion(id),
    code           VARCHAR(10) NOT NULL UNIQUE,
    ouverture_at   TIMESTAMP NOT NULL,
    expiration_at  TIMESTAMP NOT NULL,
    statut         VARCHAR(20) NOT NULL DEFAULT 'OUVERTE',
    cloture_at     TIMESTAMP,
    CONSTRAINT chk_session_statut CHECK (statut IN ('OUVERTE', 'CLOTUREE'))
);

CREATE TABLE presence (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT NOT NULL REFERENCES session(id),
    etudiant_id   BIGINT NOT NULL REFERENCES etudiant(id),
    source        VARCHAR(20) NOT NULL,
    cree_at       TIMESTAMP NOT NULL,
    CONSTRAINT chk_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE exercice (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT NOT NULL REFERENCES session(id),
    etudiant_id   BIGINT NOT NULL REFERENCES etudiant(id),
    lien          VARCHAR(500) NOT NULL,
    statut        VARCHAR(20) NOT NULL DEFAULT 'DEPOSE',
    cree_at       TIMESTAMP NOT NULL,
    maj_at        TIMESTAMP NOT NULL,
    CONSTRAINT chk_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE', 'RELU')),
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE relecture (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id    BIGINT NOT NULL REFERENCES exercice(id),
    relecteur_id   BIGINT NOT NULL REFERENCES etudiant(id),
    note           INTEGER,
    commentaire    VARCHAR(2000),
    statut         VARCHAR(20) NOT NULL DEFAULT 'ASSIGNEE',
    rendue_at      TIMESTAMP,
    CONSTRAINT chk_relecture_statut CHECK (statut IN ('ASSIGNEE', 'RENDUE')),
    CONSTRAINT chk_relecture_note CHECK (note IS NULL OR (note BETWEEN 0 AND 20)),
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id)
);

CREATE INDEX idx_etudiant_promotion ON etudiant(promotion_id);
CREATE INDEX idx_session_promotion ON session(promotion_id);
CREATE INDEX idx_presence_etudiant ON presence(etudiant_id);
CREATE INDEX idx_exercice_etudiant ON exercice(etudiant_id);
CREATE INDEX idx_relecture_relecteur ON relecture(relecteur_id);
